/**
 * AUTO-GENERATED by scripts/build-routes.js
 * Do not edit. Re-generate: node scripts/build-routes.js
 */

import { handlePasswordGeneratorRoutes as password_generator } from './password-generator.js';
import { handleJSONFormatterRoutes as json_formatter } from './json-formatter.js';
import { handleQRCodeRoutes as qr_code } from './qr-code.js';
import { handleUUIDGeneratorRoutes as uuid_generator } from './uuid-generator.js';
import { handleTimestampConverterRoutes as timestamp_converter } from './timestamp-converter.js';
import { handleColorConverterRoutes as color_converter } from './color-converter.js';
import { handleUnitConverterRoutes as unit_converter } from './unit-converter.js';
import { handleMarkdownEditorRoutes as markdown_editor } from './markdown-editor.js';
import { handleTextDiffRoutes as text_diff } from './text-diff.js';
import { handleCertificateDecoderRoutes as certificate_decoder } from './certificate-decoder.js';
import { handleCaseConverterRoutes as case_converter } from './case-converter.js';
import { handleLogViewerRoutes as log_viewer } from './log-viewer.js';
import { handleImageConverterRoutes as image_converter } from './image-converter.js';
import { handleCSSGradientRoutes as css_gradient } from './css-gradient-generator.js';
import { handleCodeMinifierRoutes as code_minifier } from './code-minifier.js';
import { handleCIDRCalculatorRoutes as cidr_calculator } from './cidr-calculator.js';
import { handleSamlDecoderRoutes as saml_decoder } from './saml-decoder.js';
import { handleHtpasswdRoutes as htpasswd_generator } from './htpasswd-generator.js';
import { handleDataConverterRoutes as yaml_toml_converter } from './yaml-toml-converter.js';
import { handleCronBuilderRoutes as cron_builder } from './cron-builder.js';
import { handleMockDataRoutes as mock_data_generator } from './mock-data-generator.js';
import { handleUserAgentDecoderRoutes as user_agent_decoder } from './user-agent-decoder.js';
import { handleSSHKeyGeneratorRoutes as ssh_key_generator } from './ssh-key-generator.js';
import { handleRegexVisualizerRoutes as regex_visualizer } from './regex-visualizer.js';
import { handleCurlStudioRoutes as curl_studio } from './curl-studio.js';
import { handleLogMaskerRoutes as log_masker } from './log-masker.js';
import { handleMermaidStudioRoutes as mermaid_studio } from './mermaid-studio.js';
import { handleJsonSchemaStudioRoutes as json_schema_studio } from './json-schema-studio.js';
import { handleCaffeinateRoutes as caffeinate } from './caffeinate.js';
import { handleEmailAnalyzerRoutes as email_analyzer } from './email-analyzer.js';
import { handleTokenCounterRoutes as token_counter } from './token-counter.js';
import { handlePromptTemplateBuilderRoutes as prompt_template_builder } from './prompt-template-builder.js';
import { handleSQLFormatterRoutes as sql_formatter } from './sql-formatter.js';
import { handleEnvVarManagerRoutes as env_var_manager } from './env-var-manager.js';
import { handleLadderGameRoutes as ladder_game } from './ladder-game.js';
import { handleRouletteWheelRoutes as roulette_wheel } from './roulette-wheel.js';
import { handleSVGOptimizerRoutes as svg_optimizer } from './svg-optimizer.js';
import { handleCSPBuilderRoutes as csp_builder } from './csp-builder.js';
import { handleSecretScannerRoutes as secret_scanner } from './secret-scanner.js';
import { handleDNSReferenceRoutes as dns_reference } from './dns-reference.js';
import { handlePortReferenceRoutes as port_reference } from './port-reference.js';
import { handleHTTPStatusReferenceRoutes as http_status_reference } from './http-status-reference.js';
import { handleBandwidthCalculatorRoutes as bandwidth_calculator } from './bandwidth-calculator.js';
import { handleWiresharkFilterRoutes as wireshark_filter } from './wireshark-filter.js';
import { handleProtocolHeadersRoutes as protocol_headers } from './protocol-headers.js';
import { handleWireguardConfigRoutes as wireguard_config } from './wireguard-config.js';
import { handleMarbleRouletteRoutes as marble_roulette } from './marble-roulette.js';
import { handleTokenStudioRoutes as token_studio } from './token-studio.js';
import { handleEncodingWorkbenchRoutes as encoding_workbench } from './encoding-workbench.js';
import { handleOAuthDebuggerRoutes as oauth_debugger } from './oauth-debugger.js';
import { handleWebhookDebuggerRoutes as webhook_debugger } from './webhook-debugger.js';
import { handleGithubAutomationRoutes as github_automation } from './github-automation.js';
import { handlePipeRoutes as pipe } from './pipe.js';
import { handleChangelogRoutes as changelog } from './changelog.js';

export const handlersById = {
  'password-generator': password_generator,
  'json-formatter': json_formatter,
  'qr-code': qr_code,
  'uuid-generator': uuid_generator,
  'timestamp-converter': timestamp_converter,
  'color-converter': color_converter,
  'unit-converter': unit_converter,
  'markdown-editor': markdown_editor,
  'text-diff': text_diff,
  'certificate-decoder': certificate_decoder,
  'case-converter': case_converter,
  'log-viewer': log_viewer,
  'image-converter': image_converter,
  'css-gradient': css_gradient,
  'code-minifier': code_minifier,
  'cidr-calculator': cidr_calculator,
  'saml-decoder': saml_decoder,
  'htpasswd-generator': htpasswd_generator,
  'yaml-toml-converter': yaml_toml_converter,
  'cron-builder': cron_builder,
  'mock-data-generator': mock_data_generator,
  'user-agent-decoder': user_agent_decoder,
  'ssh-key-generator': ssh_key_generator,
  'regex-visualizer': regex_visualizer,
  'curl-studio': curl_studio,
  'log-masker': log_masker,
  'mermaid-studio': mermaid_studio,
  'json-schema-studio': json_schema_studio,
  'caffeinate': caffeinate,
  'email-analyzer': email_analyzer,
  'token-counter': token_counter,
  'prompt-template-builder': prompt_template_builder,
  'sql-formatter': sql_formatter,
  'env-var-manager': env_var_manager,
  'ladder-game': ladder_game,
  'roulette-wheel': roulette_wheel,
  'svg-optimizer': svg_optimizer,
  'csp-builder': csp_builder,
  'secret-scanner': secret_scanner,
  'dns-reference': dns_reference,
  'port-reference': port_reference,
  'http-status-reference': http_status_reference,
  'bandwidth-calculator': bandwidth_calculator,
  'wireshark-filter': wireshark_filter,
  'protocol-headers': protocol_headers,
  'wireguard-config': wireguard_config,
  'marble-roulette': marble_roulette,
  'token-studio': token_studio,
  'encoding-workbench': encoding_workbench,
  'oauth-debugger': oauth_debugger,
  'webhook-debugger': webhook_debugger,
  'github-automation': github_automation,
  'pipe': pipe,
  'changelog': changelog,
};
