/**
 * Build script for UI assets
 * Generates a bundled Tailwind stylesheet for the worker to serve locally.
 */

import { promises as fs } from 'fs';
import { createHash } from 'crypto';
import { fileURLToPath } from 'url';
import path from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.resolve(__dirname, '..');
const cssPath = path.resolve(projectRoot, 'dist', 'styles.css');
const outputPath = path.resolve(projectRoot, 'src', 'utils', 'bundled-styles.js');

async function buildUi() {
  console.log('Building UI assets...');

  const css = await fs.readFile(cssPath, 'utf8').catch((error) => {
    throw new Error(`Unable to read compiled stylesheet at ${cssPath}: ${error.message}`);
  });

  const hash = createHash('sha256').update(css).digest('hex').slice(0, 16);

  const banner = `// Auto-generated by scripts/build-ui.js. Do not edit manually.\n`;
  const exportSource = `${banner}export const bundledStylesHash = '${hash}';\nexport const bundledStyles = ${JSON.stringify(css)};\n`;

  await fs.writeFile(outputPath, exportSource, 'utf8');

  console.log(`✓ Generated bundled styles (${css.length} bytes, hash ${hash}).`);
  console.log(`✓ Output written to ${outputPath}`);
}

buildUi().catch((error) => {
  console.error('✗ UI build failed:', error);
  process.exit(1);
});
